<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("MENU", "N");
$APPLICATION->SetTitle("Вопросы и ответы");
?><div>
	 В данном разделе приведены ответы на часто задаваемые вопросы посетителей вашего будущего сайта. Использование данного раздела позволит сократить нагрузку на операторов и повысить удовлетворенность ваших клиентов.&nbsp;
</div>
 <!-- &nbsp;--><?//$APPLICATION->IncludeComponent(
//	"bitrix:menu",
//	".default",
//	array(
//		"ALLOW_MULTI_SELECT" => "N",
//		"CHILD_MENU_TYPE" => "podrazdel_faq",
//		"DELAY" => "N",
//		"MAX_LEVEL" => "3",
//		"MENU_CACHE_GET_VARS" => array(
//		),
//		"MENU_CACHE_TIME" => "3600",
//		"MENU_CACHE_TYPE" => "N",
//		"MENU_CACHE_USE_GROUPS" => "Y",
//		"ROOT_MENU_TYPE" => "left",
//		"USE_EXT" => "Y",
//		"COMPONENT_TEMPLATE" => ".default"
//	),
//	false
//);?>
<div>
 <br>
</div>
  <?//$APPLICATION->IncludeComponent(
//	"bitrix:news",
//	"faq",
//	array(
//		"ADD_ELEMENT_CHAIN" => "N",
//		"ADD_SECTIONS_CHAIN" => "N",
//		"AJAX_MODE" => "N",
//		"AJAX_OPTION_ADDITIONAL" => "",
//		"AJAX_OPTION_HISTORY" => "N",
//		"AJAX_OPTION_JUMP" => "N",
//		"AJAX_OPTION_STYLE" => "Y",
//		"BROWSER_TITLE" => "-",
//		"CACHE_FILTER" => "N",
//		"CACHE_GROUPS" => "N",
//		"CACHE_TIME" => "100000",
//		"CACHE_TYPE" => "A",
//		"CHECK_DATES" => "Y",
//		"COMPONENT_TEMPLATE" => "faq",
//		"COUNT_IN_LINE" => "3",
//		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
//		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
//		"DETAIL_DISPLAY_TOP_PAGER" => "N",
//		"DETAIL_FIELD_CODE" => array(
//			0 => "",
//			1 => "",
//		),
//		"DETAIL_PAGER_SHOW_ALL" => "Y",
//		"DETAIL_PAGER_TEMPLATE" => "",
//		"DETAIL_PAGER_TITLE" => "Страница",
//		"DETAIL_PROPERTY_CODE" => array(
//			0 => "TITLE_BUTTON",
//			1 => "LINK_BUTTON",
//			2 => "",
//		),
//		"DETAIL_SET_CANONICAL_URL" => "N",
//		"DISPLAY_BOTTOM_PAGER" => "Y",
//		"DISPLAY_NAME" => "Y",
//		"DISPLAY_TOP_PAGER" => "N",
//		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
//		"IBLOCK_ID" => "26",
//		"IBLOCK_TYPE" => "aspro_allcorp3_content",
//		"IMAGE_POSITION" => "left",
//		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
//		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
//		"LIST_FIELD_CODE" => array(
//			0 => "PREVIEW_TEXT",
//			1 => "PREVIEW_PICTURE",
//			2 => "",
//		),
//		"LIST_PROPERTY_CODE" => array(
//			0 => "TITLE_BUTTON",
//			1 => "LINK_BUTTON",
//			2 => "",
//		),
//		"MESSAGE_404" => "",
//		"META_DESCRIPTION" => "-",
//		"META_KEYWORDS" => "-",
//		"NEWS_COUNT" => "20",
//		"PAGER_BASE_LINK_ENABLE" => "N",
//		"PAGER_DESC_NUMBERING" => "N",
//		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
//		"PAGER_SHOW_ALL" => "N",
//		"PAGER_SHOW_ALWAYS" => "N",
//		"PAGER_TEMPLATE" => ".default",
//		"PAGER_TITLE" => "Новости",
//		"PREVIEW_TRUNCATE_LEN" => "",
//		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_1",
//		"SEF_FOLDER" => "/company/faq/",
//		"SEF_MODE" => "Y",
//		"SET_LAST_MODIFIED" => "N",
//		"SET_STATUS_404" => "N",
//		"SET_TITLE" => "Y",
//		"SHOW_404" => "N",
//		"SHOW_ASK_QUESTION_BLOCK" => "Y",
//		"SHOW_DETAIL_LINK" => "Y",
//		"SHOW_SECTION_NAME" => "N",
//		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
//		"SHOW_TABS" => "Y",
//		"SORT_BY1" => "SORT",
//		"SORT_BY2" => "ID",
//		"SORT_ORDER1" => "ASC",
//		"SORT_ORDER2" => "DESC",
//		"STRICT_SECTION_CHECK" => "N",
//		"S_ASK_QUESTION" => "",
//		"USE_CATEGORIES" => "N",
//		"USE_FILTER" => "Y",
//		"USE_PERMISSIONS" => "N",
//		"USE_RATING" => "N",
//		"USE_REVIEW" => "N",
//		"USE_RSS" => "N",
//		"USE_SEARCH" => "N",
//		"USE_SHARE" => "N",
//		"VIEW_TYPE" => "accordion",
//		"FILTER_NAME" => "",
//		"FILTER_FIELD_CODE" => array(
//			0 => "",
//			1 => "",
//		),
//		"FILTER_PROPERTY_CODE" => array(
//			0 => "",
//			1 => "",
//		),
//		"SEF_URL_TEMPLATES" => array(
//			"news" => "",
//			"section" => "",
//			"detail" => "",
//		)
//	),
//	false
//);?>
<div class="row row__flex">
	<div class="col-md-4 left__menu">
		 <?$APPLICATION->IncludeComponent(
	"bitrix:menu",
	"left_vertical",
	Array(
		"ALLOW_MULTI_SELECT" => "N",
		"CHILD_MENU_TYPE" => "podrazdel_faq",
		"DELAY" => "N",
		"MAX_LEVEL" => "3",
		"MENU_CACHE_GET_VARS" => array(""),
		"MENU_CACHE_TIME" => "3600",
		"MENU_CACHE_TYPE" => "N",
		"MENU_CACHE_USE_GROUPS" => "Y",
		"ROOT_MENU_TYPE" => "left",
		"USE_EXT" => "Y"
	)
);?>
	</div>
	<div class="col-md-8">
		<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"faq_answers", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "100000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "faq_answers",
		"COUNT_IN_LINE" => "3",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "TITLE_BUTTON",
			1 => "LINK_BUTTON",
			2 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"IBLOCK_ID" => "26",
		"IBLOCK_TYPE" => "aspro_allcorp3_content",
		"IMAGE_POSITION" => "left",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "TITLE_BUTTON",
			1 => "LINK_BUTTON",
			2 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_1",
		"SEF_FOLDER" => "/faq/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ASK_QUESTION_BLOCK" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_SECTION_NAME" => "N",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SHOW_TABS" => "Y",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "DESC",
		"STRICT_SECTION_CHECK" => "N",
		"S_ASK_QUESTION" => "",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"VIEW_TYPE" => "accordion",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"TEMPLATE_THEME" => "blue",
		"MEDIA_PROPERTY" => "",
		"SLIDER_PROPERTY" => "",
		"SECTIONS_TYPE_VIEW" => "FROM_MODULE",
		"SECTION_TYPE_VIEW" => "FROM_MODULE",
		"ELEMENT_TYPE_VIEW" => "FROM_MODULE",
		"USE_DETAIL_TABS" => "FROM_MODULE",
		"SKU_IBLOCK_ID" => "1",
		"SKU_SORT_ORDER" => "asc",
		"SKU_SORT_FIELD2" => "sort",
		"SKU_SORT_ORDER2" => "asc",
		"CHANGE_TEXT_AND_CARDS" => "N",
		"SHOW_SECTION_DESCRIPTION" => "Y",
		"SHOW_SECTION" => "Y",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_CHILD_SECTIONS" => "Y",
		"SHOW_CHILD_ELEMENTS" => "N",
		"ELEMENTS_ITEMS_OFFSET" => "Y",
		"ELEMENTS_COUNT" => "2",
		"DETAIL_USE_TAGS" => "N",
		"SHOW_CATEGORY" => "N",
		"PROPERTIES_DISPLAY_TYPE" => "TABLE",
		"T_DESC" => "",
		"T_CHAR" => "",
		"SHOW_BIG_GALLERY" => "Y",
		"TYPE_BIG_GALLERY" => "BIG",
		"T_BIG_GALLERY" => "",
		"BIG_GALLERY_PROP_CODE" => "-",
		"T_VIDEO" => "",
		"T_DOCS" => "",
		"DOCS_PROP_CODE" => "-",
		"T_FAQ" => "",
		"T_REVIEWS" => "",
		"T_VACANCY" => "",
		"T_STAFF" => "",
		"T_SALE" => "",
		"T_NEWS" => "",
		"T_ARTICLES" => "",
		"T_SERVICES" => "",
		"T_PROJECTS" => "",
		"T_PARTNERS" => "",
		"T_GOODS" => "",
		"T_TARIFFS" => "",
		"SHOW_DOPS" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_BLOCKS_ORDER" => "order_form,sale,tizers,tabs,big_gallery,services,projects,news,articles,staff,partners,vacancy,goods,comments,tariffs",
		"DETAIL_BLOCKS_TAB_ORDER" => "desc,char,video,docs,faq,reviews,dops",
		"S_ORDER_SERVISE" => "",
		"FORM_ID_ORDER_SERVISE" => "",
		"TAGS_CLOUD_ELEMENTS" => "150",
		"PERIOD_NEW_TAGS" => "",
		"DISPLAY_AS_RATING" => "rating",
		"FONT_MAX" => "50",
		"FONT_MIN" => "10",
		"COLOR_NEW" => "3E74E6",
		"COLOR_OLD" => "C0C0C0",
		"TAGS_CLOUD_WIDTH" => "100%",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE_PATH#",
			"detail" => "",
		)
	),
	false
);?>
	</div>
</div>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>